version: "3.9"
services:
  nats:
    image: nats:2.10
    command: ["-js"]
    ports:
      - "${NATS_PORT:-4222}:4222"
      - "${NATS_MON_PORT:-8222}:8222"
    healthcheck:
      test: ["CMD", "nats", "server", "report", "varz", "-s", "nats://localhost:4222"]
      interval: 5s
      timeout: 3s
      retries: 10