# deny.toml
[graph]
targets = []

[advisories]
version = 2
yanked = "warn"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "allow"  # Workspace dependencies use wildcard versions

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
version = 2
allow = [
    "MIT",
    "MIT-0",  # MIT No Attribution - needed for borrow-or-share crate
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
    "CC0-1.0",
    "Unlicense",
    "CDLA-Permissive-2.0",  # Community Data License Agreement - needed for webpki-roots
]
confidence-threshold = 0.8
private = { ignore = true }  # Allow private/unlicensed workspace crates