# deny.toml
[graph]
targets = []

[advisories]
version = 2
yanked = "warn"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "allow"  # Workspace dependencies use wildcard versions

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
    "CC0-1.0",
    "Unlicense",
]
confidence-threshold = 0.8
# Workspace crates don't have licenses yet - allow them specifically
[[licenses.exceptions]]
allow = ["Unlicense"]
crate = "demonctl"

[[licenses.exceptions]]
allow = ["Unlicense"]
crate = "engine"

[[licenses.exceptions]]
allow = ["Unlicense"]
crate = "runtime"

[[licenses.exceptions]]
allow = ["Unlicense"]
crate = "operate-ui"

[[licenses.exceptions]]
allow = ["Unlicense"]
crate = "wards"

[[licenses.exceptions]]
allow = ["Unlicense"]
crate = "capsules_echo"

[[licenses.exceptions]]
allow = ["Unlicense"]
crate = "bootstrapper-demonctl"