[package]
name = "runtime"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
capsules_echo = { path = "../capsules/echo" }
