[package]
name = "capsules_echo"
version = "0.0.1"
edition = "2021"
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
envelope = { path = "../../crates/envelope" }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }