name: contracts-validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  contracts-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.82.0
      - uses: Swatinem/rust-cache@v2
      - name: Validate contracts
        run: ./scripts/contracts-validate.sh
