name: protection-audit

on:
  schedule:
    - cron: '23 4 * * *'
  pull_request:
    types: [opened, synchronize, reopened, labeled, ready_for_review]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get default branch
        id: repo
        run: |
          gh api repos/${{ github.repository }} --jq .default_branch > default_branch.txt
          echo "branch=$(cat default_branch.txt)" >> "$GITHUB_OUTPUT"
      - name: Assert replies guard required when flagged
        shell: bash
        run: |
          set -euo pipefail
          BR="${{ steps.repo.outputs.branch }}"
          if [[ -f .github/flags/guard-required ]]; then
            echo "Flag present — asserting replies-guard is a required status check"
            ctx=$(gh api repos/:owner/:repo/branches/$BR/protection -q '.required_status_checks.contexts')
            echo "$ctx" | jq -e 'index("review-threads-guard (PR) / guard") != null' >/dev/null || {
              echo "::error::Required checks missing: review-threads-guard (PR) / guard"; exit 1; }
          else
            echo "Flag absent — skipping replies-guard assertion (burn-in phase)"
          fi

  note-missing-token:
    if: ${{ secrets.PROTECTION_TOKEN == '' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'PROTECTION_TOKEN not set; audit uses GITHUB_TOKEN-only calls.'
