name: review-inline-comment (manual)

on:
  workflow_dispatch:
    inputs:
      pr:
        description: "PR number to comment on"
        required: true
        type: number
      file:
        description: "Path to file (at PR head)"
        required: true
        type: string
      match:
        description: "Substring to find in the file to compute line number"
        required: true
        type: string
      body:
        description: "Comment body"
        required: false
        default: "Guard demo: please address"
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post inline review comment via github-actions
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = parseInt(core.getInput('pr'));
            const file = core.getInput('file');
            const match = core.getInput('match');
            const body = core.getInput('body') || 'Guard demo: please address';

            const {owner, repo} = context.repo;
            const pr = await github.rest.pulls.get({ owner, repo, pull_number: prNumber });
            const commit_id = pr.data.head.sha;

            const contentRes = await github.rest.repos.getContent({ owner, repo, path: file, ref: commit_id });
            if (Array.isArray(contentRes.data)) {
              core.setFailed(`Path ${file} is a directory`);
              return;
            }
            const buf = Buffer.from(contentRes.data.content, contentRes.data.encoding);
            const text = buf.toString('utf8');
            const lines = text.split(/\r?\n/);
            const idx = lines.findIndex(l => l.includes(match));
            if (idx === -1) {
              core.setFailed(`Could not find match '${match}' in ${file}@${commit_id}`);
              return;
            }
            const line = idx + 1;

            await github.rest.pulls.createReviewComment({
              owner,
              repo,
              pull_number: prNumber,
              body,
              commit_id,
              path: file,
              side: 'RIGHT',
              line,
            });
            core.info(`Posted inline comment on PR #${prNumber} at ${file}:${line}`);
